# Site settings
title:       Heroes of Programming
email:       iulian@heroesofprogramming.com
author:      Iulian Gulea
description: "Learn Programming in JavaScript and Python and basic programming concepts explained in a simple and clear manner."
baseurl:     ""
url:         "http://blog.heroesofprogramming.com"
date_format: "%b %-d, %Y"

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: UA-84704450-1
google_tag_manager:
# Bing services
bing_verification:

# Optional features
animated:             true
show_related_posts:   false
show_post_footers:    true
show_social_icons:    true
ajaxify_contact_form: true
enable_mathjax: true
extended_fonts: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: heroesofprogramming

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username: 
bitbucket_username:
stackoverflow_id: 3120525
twitter_username: heroesofprog
facebook_username: HeroesOfProgramming
skype_username:
steam_nickname:
google_plus_id:
linkedin_username: iuliangulea
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: true
share_hackernews: false

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         "Sharing buttons! No pressure - the choice to share is yours, conscious and mindful."
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting me. I will reply as soon as possible.'
  og_locale: 'en_US'

# Build settings
timezone:     Europe/Chisinau
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     8
sass:
  compressed: true
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-auto-image
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]

# Collections
collections:
  quizzes_javascript:
    output: true
    permalink: /quizzes/js/:title/

jekyll-archives:
  enabled: 
    - categories
    - tags
    - year
    - month
  layouts: 
    year: year-archive
    month: month-archive
    category: category-tag-archive
    tag: category-tag-archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

# Jekyll-auto-image settings
image: /assets/images/heroes/HeroesOfProgramming.png